[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
num-traits = { version = "0.2.17", features = [] }
num = { version = "0.4.1", features = [] }